#!/bin/bash
# Using eye to translate from and to N3S to N3P
# Patrick May 2024

EYE="${EYE_BIN:-eye}"
SWIPL="${SWIPL_BIN:-swipl}"
ME=$(dirname "$0")

FILE=$1

if [ "${FILE}" == "" ]; then
    echo "usage: $0 file"
    exit 1
fi

TMPDIR=$(mktemp -d)

${ME}/n32s.sh $1 > ${TMPDIR}/program.n3p

cat <<EOF > ${TMPDIR}/query.pl 
:- consult('${ME}/core.pl').

run :-
    run('${TMPDIR}/program.n3p').
EOF

${SWIPL} -f ${TMPDIR}/query.pl -g run,halt > ${TMPDIR}/result.pl

${ME}/s2n3.sh ${TMPDIR}/result.pl 

CONTRADICTION=$(cat ${TMPDIR}/result.pl | grep "contradicton detected")

if [ "${CONTRADICTION}" == "" ]; then
    CODE=0
else
    echo "***contradicton detected***"
    CODE=2
fi

rm ${TMPDIR}/program.n3p
rm ${TMPDIR}/query.pl
rm ${TMPDIR}/result.pl
rmdir ${TMPDIR}

exit ${CODE}
